#!/usr/bin/env bash
# Scaffold a per-project stack under projects/<slug>/.
#
# One checkout runs any number of stacks. A project is a directory holding the
# things that differ between them — scoped credentials, the host port, the repo
# path, symphony's WORKFLOW.md — layered on top of the root .env and
# symphony/.env, which hold what they share.
#
#   ./scripts/new-project.sh <slug> [<host-repo-path>] [<port>]
#
# This replaces the old behaviour of copying the whole checkout to a sibling
# directory. That model made every project a full duplicate of the harness, so
# an upgrade had to be applied N times and the copies drifted. Nothing about
# the images or the compose files was ever per-project; only the env was.
set -euo pipefail

usage() {
    cat <<EOF
Usage: $0 <slug> [<host-repo-path>] [<port>]

  slug             Short name. Becomes projects/<slug>/, the compose project
                   name, and the container/volume name suffix.
  host-repo-path   Path on the host to bind-mount as /workspace.
                   Default: ./projects/<slug>/repo
  port             Host port for the opencode web/desktop frontend.
                   Default: the next free port starting at 4096.

Example:
  $0 acme-api ~/code/acme-api

Then:
  ./scripts/opencode -p acme-api
  ./scripts/symphony -p acme-api check
EOF
}

case "${1:-}" in
    -h|--help) usage; exit 0 ;;
    "") usage; exit 1 ;;
esac

SLUG="$1"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

# The slug is a path component and a compose project name before it is anything
# else, so it is validated as one.
case "${SLUG}" in
    *[!A-Za-z0-9._-]*|.*|-*)
        echo "invalid slug: ${SLUG}" >&2
        echo "  letters, digits, dot, underscore and dash; must start with a letter or digit" >&2
        exit 1 ;;
esac

DEST="projects/${SLUG}"
[ -e "${DEST}" ] && { echo "${DEST} already exists." >&2; exit 1; }

REPO_PATH="${2:-./${DEST}/repo}"
PORT="${3:-}"

# port_taken PORT — busy on the host, or already claimed by another project.
# Both matter: two projects recorded on one port collide the first time they
# run together, long after the second was created.
port_taken() {
    local p="$1"
    ss -ltn 2>/dev/null | awk '{print $4}' | grep -q "[:.]${p}\$" && return 0
    grep -rhsE "^OPENCODE_PORT=${p}\$" projects/*/.env >/dev/null 2>&1 && return 0
    return 1
}

# The opencode-pty viewer port is derived by prepending a '1' (4096 -> 14096),
# so a candidate whose viewer port is taken is no good either — oc-publish would
# fail to bind its second socat leg and the whole stack would not come up.
if [ -z "${PORT}" ]; then
    PORT=4096
    while [ "${PORT}" -lt 4196 ] && { port_taken "${PORT}" || port_taken "1${PORT}"; }; do
        PORT=$((PORT + 1))
    done
    [ "${PORT}" -lt 4196 ] || { echo "no free port in 4096-4195." >&2; exit 1; }
fi

mkdir -p "${DEST}/config" "${DEST}/queue" "${DEST}/workspaces"

# --- projects/<slug>/.env — the AGENT-visible layer ---------------------------
# Only overrides. Everything not named here is inherited from the root .env,
# which is what keeps this file short enough to actually read.
cat > "${DEST}/.env" <<EOF
# Per-project overrides for '${SLUG}', layered on the root .env (last wins).
# Generated by scripts/new-project.sh; edit freely.
#
# Read by ./scripts/opencode -p ${SLUG} and ./scripts/symphony -p ${SLUG}, and
# handed to the AGENT's container by docker-compose.yml. Symphony's own settings
# go in symphony.env next to this file — never here.
#
# Same parser rule as the root .env: comments on their OWN lines, never inline
# after a value.

PROJECT_SLUG=${SLUG}
OPENCODE_PORT=${PORT}
REPO_PATH=${REPO_PATH}

# === Scoped credentials ======================================================
# The reason a project has its own env file at all. A GitLab project access
# token reaches exactly one project, so it cannot be shared between stacks even
# in principle — and under symphony it IS the containment boundary
# (docs/SYMPHONY.md §1). Uncomment and fill in what this project needs.
#
# For an unattended stack this must be a PROJECT access token, Developer role,
# scopes api + write_repository. Never your personal PAT.
#GITLAB_PAT=

# === Credentials this project should NOT have ================================
# Blanking an inherited value keeps that MCP server out of the stack entirely —
# absent, not disabled, because each one auto-enables on credential presence.
# For a symphony project that is the point: docs/SYMPHONY.md §2. Uncomment the
# ones this project has no business reaching.
#BITBUCKET_PAT=
#JIRA_PAT=
#JFROG_PAT=
#CONFLUENCE_PAT=
#MFILES_PAT=

# === Safety switches =========================================================
# Off by default, same as the root .env. Symphony needs remote git on; an
# interactive project usually does not.
#ALLOW_REMOTE_GIT=1
#GIT_REMOTE_ALLOWLIST=gitlab.internal.example/mygroup/myproject
#ALLOW_GITLAB_WRITE=1
#GITLAB_WRITE_PROJECTS=mygroup/myproject
EOF

# --- projects/<slug>/symphony.env — the LAUNCHER-only layer -------------------
# Never named by any `env_file:` directive, which is what keeps the tracker
# token out of the agent's environment.
cat > "${DEST}/symphony.env" <<EOF
# Per-project symphony overrides for '${SLUG}', layered on symphony/.env.
# Generated by scripts/new-project.sh; edit freely.
#
# Read ONLY by ./scripts/symphony -p ${SLUG}. docker-compose.yml never names
# this file, so nothing in it reaches the agent's container — which is the whole
# reason symphony's tracker token lives here and not in .env beside it.
#
# The queue, workspaces and config paths are derived from the project directory
# and need no entry here. Set one only to move it somewhere else.

# SYMPHONY's token, for tracker.kind: gitlab. A PROJECT access token with the
# REPORTER role and api scope: it can read and write issues on this one project
# and CANNOT push code. The agent's Developer token is GITLAB_PAT, in .env next
# to this file. Two tokens, neither able to do the other's job.
#
# Left COMMENTED OUT deliberately. Absent means "inherit from symphony/.env",
# which is what a group access token over a sandbox group is for — one
# credential covering several projects (docs/SYMPHONY.md §1). An empty value
# here would override that shared token with nothing and report it as missing.
# Uncomment to give this project its own; ./scripts/symphony check tells you
# which of the two you are running with.
#SYMPHONY_GITLAB_TOKEN=
EOF

# The WORKFLOW.md is left for the user: choosing a tracker is the first real
# decision about a symphony project, and a default would make it silently.
cat <<EOF
created ${DEST}
  slug:  ${SLUG}
  port:  ${PORT} (viewer 1${PORT})
  repo:  ${REPO_PATH}

next:
  \$EDITOR ${DEST}/.env            # scoped credentials for this project
  ./scripts/opencode -p ${SLUG}

for an unattended (symphony) project, also:
  cp symphony/WORKFLOW.md.example ${DEST}/config/WORKFLOW.md          # file queue
  cp symphony/WORKFLOW.gitlab.md.example ${DEST}/config/WORKFLOW.md   # GitLab issues
  \$EDITOR ${DEST}/config/WORKFLOW.md
  \$EDITOR ${DEST}/symphony.env    # the Reporter token
  ./scripts/symphony -p ${SLUG} check

layout and layering rules: projects/README.md
EOF
